config/routes.rb
QiitaHack::Application.routes.draw do
  resources :users do
    member do
      get 'update_qiita'
      post 'update_qiita'
    end
    collection do
      get 'signup'
    end
  end

  root :to => 'users#signup'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :qiita_update_at, :repo_name, :token, :url_name, :new_flag, :password
  before_create :set_qiita_token

  def set_qiita_token
    @qiita = Qiita.new({ :url_name => self.url_name, :password => self.password })
    self.token = @qiita.token
  end

  def auth_qiita
    @qiita = Qiita.new({ :token => self.token})
    @basedir="#{Rails.public_path}/users/#{self.url_name}"
  end

  def upload_contents(contents)
    title = contents[0]
    body = contents[1..-1].join("").strip.chomp
    item = { :title => title, :body => body, :tags => [{ :name => 'default'}], :private => false}
    @qiita.post_item item
  end

  def pull_or_clone_from_github(repo)
    # @repo="git://github.com/#{self.url_name}/#{self.repo_name}"
    if self.new_flag
      `mkdir -p #{@basedir}`
      `git clone #{repo} #{@basedir}`
      self.new_flag = false
      self.save
    else
      `cd #{@basedir}; git pull`
    end
  end

  def publish_qiita
    Dir.glob("#{@basedir}/*.md") do |f|
      contents = open(f).readlines
      upload_contents(contents)
    end
  end

  def qiita
    @qiita
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/qiita_controller.rb
class QiitaController < ApplicationController

  def update
    @user = User.find(:first)
    @user.auth_qiita
    # @user.pull_or_clone_from_github
    @user.publish_qiita
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def update_qiita
    @user = User.find(params[:id])
    @user.auth_qiita

    if request.post?
      @payload = JSON.parse(params[:payload])
      @github_repo = @payload["repository"]["url"]
      @user.pull_or_clone_from_github(@github_repo)
    else
      @payload = "get"
      @user.pull_or_clone_from_github(@github_repo)
    end

    @user.publish_qiita
  end

  def signup
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qiita_helper.rb
module QiitaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "QiitaGithub" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">QiitaGithub</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/qiita/update.html.erb
<%= @user %>
<%= @user.qiita.user_items %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_name %><br />
    <%= f.text_field :url_name %>
  </div>
  <div class="field">
    <%= f.label :repo_name %><br />
    <%= f.text_field :repo_name %>
  </div>
  <div class="field">
    <%= f.label :new_flag %><br />
    <%= f.select :new_flag, {'new' => true, 'not new' => false} %>
  </div>
  <div class="field">
    <%= f.label :qiita_update_at %><br />
    <%= f.datetime_select :qiita_update_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Url name</th>
    <th>Token</th>
    <th>Qiita update at</th>
    <th>New flag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.url_name %></td>
    <td><%= user.repo_name %></td>
    <td><%= user.qiita_update_at %></td>
    <td><%= user.new_flag %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

このURLをgithubのWebHookURLsに登録してください。
<div class='url'>
<%= update_qiita_user_url(@user) %>
</div>



<%= link_to 'Qiitaに反映', update_qiita_user_url(@user) %>

<p>
  <b>Url name:</b>
  <%= @user.url_name %>
</p>

<p>
  <b>Repo name:</b>
  <%= @user.repo_name %>
</p>

<p>
  <b>token:</b>
  <%= @user.token[0..3] %>...
</p>

<p>
  <b>New flag:</b>
  <%= @user.new_flag %>
</p>

<p>
  <b>Qiita update at:</b>
  <%= @user.qiita_update_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signup.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_name %><br />
    <%= f.text_field :url_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit('Sign up') %>
  </div>
<% end %>

app/views/users/update_qiita.html.erb
<%= @payload %>